### ISSUE TITLE
login.htm is missing

### ISSUE THREAD

**Issue by danielsantiago** [Nexudus/nexudus-spaces-default-theme#1]
Hi,

I'm trying to modify the login.htm but I can't find it in the files.

**Comment by Nexudus** [comment]
Hi Daniel,

Unfortunately, to keep things as secure as possible, the login page cannot
be modified other than by uploading your space logo from System > Spaces.

Adrian

--
*This email was typed by hand and for you - we don't use any auto-response
systems. *
-- 
*Adrian Palacios*
E: adrian@nexudus.com
T: +44.776.555.6838

[image: Néxudus]



adrian@nexudus.com <info@nexudus.com>
http://coworking.nexudus.com

**Comment by danielsantiago** [comment]
I found a bug in the Login page that prevent the Login DIV from centering the div when the windows size is as small in bootstrap. You can fix it by adding the class "col-sm-offset-3" to the "body > container > row > div" element. (Right now it has theses classes: "col-sm-6 col-md-4 col-md-offset-4")

Thanks for the fast response Adrian.

**Comment by Nexudus** [comment]
Thanks Daniel. We'll have a look and try to push it in this Sunday's
release.

Adrian

--
*This email was typed by hand and for you - we don't use any auto-response
systems. *
-- 
*Adrian Palacios*
E: adrian@nexudus.com
T: +44.776.555.6838

[image: Néxudus]



adrian@nexudus.com <info@nexudus.com>
http://coworking.nexudus.com

**Comment by iamkevingreen** [comment]
Is there anyway as an alternative that some login.css could exist? I would at least like to override the bootstrap styles, it's very of putting for the rest of the brand I represent especially with everything else that's so customizable this seems like a fairly large oversight. 

Or at least load the css.css from the custom theme styles?

**Comment by Nexudus** [comment]
Hi Kevin,

Not at this point, the login page cannot be style at the moment, mainly due
to PCI/DSS checks. We are thinking of alternative ways of passing those
tests and still have some styling applied to those pages.

Adrian

--
*This email was typed by hand and for you - we don't use any auto-response
systems. *
-- 
*Adrian Palacios*
E: adrian@nexudus.com
T: +44.776.555.6838

[image: Néxudus]



adrian@nexudus.com <info@nexudus.com>
http://nexudus.com

**Comment by iamkevingreen** [comment]
Mmm very well then, I've made a fork of this with some es6, webpack, gulp fun times. Do you guys have some kind of login api hooks? Is the `access control` checkin a login? or is that something different? (I'm pretty new to the system so trying to figure out an alternative to the login, if there isn't one i'll stop poking around) I know a few sites that were built with nexudus and it seems like most people don't do very much in terms of customizing the frontend. I intend on doing the opposite of that lol. But none of the examples have a custom login so I guess that's the way it is right now ;)

Is there any chance to simply modernize the current login a bit? (I realize the login endpoint just adds that hash to track which space you're coming from so I get why you can't do css injection) It seems to just be the default bootstrap styles and I think pretty much anything other than that would look nicer :(

**Comment by Nexudus** [comment]
Hi Kevin,

You can implement your own login page indeed.

Hit

POST https://spaces.nexudus.com/api/sys/users/validate with { email:
"..@..", password: "xyz" } and will return a user object if the credentials
are right.

or

POST https://spaces.nexudus.com/api/sys/users/token with { email: "..@..",
password: "xyz" } and will return a one-time token which you can the use in

https://XYZ.spaces.nexudus.com/en/user/login?t=TOKEN to log the user in the
site.

Here is an example of a site using a custom login page:
https://app.bespokesf.co/accounts/login/

Adrian

--
*This email was typed by hand and for you - we don't use any auto-response
systems. *
-- 
*Adrian Palacios*
E: adrian@nexudus.com
T: +44.776.555.6838

[image: Néxudus]



adrian@nexudus.com <info@nexudus.com>
http://nexudus.com

**Comment by iamkevingreen** [comment]
💯  awesome thank you dude!
