### ISSUE TITLE
new design

### ISSUE THREAD

**Issue by fballiano** [Nexudus/nexudus-spaces-default-theme#2]
Hi, is there any news on the new design that should have been rolled our a few weeks ago?

thank you very much
regards

**Comment by Nexudus** [comment]
Almost there, Fabrizio. We've been busy updating the mobile app, but were
are almost there.

**Comment by Nexudus** [comment]
Hi Fabrizio. The new theme is now available at https://github.com/Nexudus/Nexudus-Space-Dos-Theme

**Comment by fballiano** [comment]
yeah! is there a place where it's possible to check a preview?

**Comment by Nexudus** [comment]
New accounts from a few months ago have the new theme in them. You can also head to demoaccount.spaces.nexudus.com
