### ISSUE TITLE
template files

### ISSUE THREAD

**Issue by whitnelson** [Nexudus/nexudus-spaces-default-theme#3]
I'm noticing there are files in the live implementation that aren't present here. For example:

core_priceplans_table_scripts.htm
gateway_payment_form.htm

... just to name a few. Am I missing something?

Thanks!

**Comment by Nexudus** [comment]
Hi Whit. Please use the repository for the theme you are using in your account. In this case https://github.com/Nexudus/Nexudus-Space-Dos-Theme
